### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sefffal** [rsantet/multiESS#1]
Hello @rsantet ! I am interested to try out this code. Would you mind posting a license (MIT, ideally) so that others can re-use it?

Thanks very much!

**Comment by rsantet** [comment]
Hello @sefffal 
I added the MIT license. Do not hesitate to cite the corresponding paper by Vats and al., as well as the pre-existing implementations in other languages (in particular the original MATLAB one).
Best of luck with your research!
